import React, { useEffect, useState } from 'react';
import { motion, AnimatePresence, useAnimation } from 'framer-motion';

import eggEmber from '../assets/art/egg-ember.webp';
import eggFrost from '../assets/art/egg-frost.webp';
import eggStone from '../assets/art/egg-stone.webp';
import eggShadow from '../assets/art/egg-shadow.webp';
import eggGlimmer from '../assets/art/egg-glimmer.webp';
import eggStorm from '../assets/art/egg-storm.webp';

import emberEgg0 from '../assets/art/ember-egg-0.webp';
import emberEgg1 from '../assets/art/ember-egg-1.webp';
import emberEgg2 from '../assets/art/ember-egg-2.webp';
import emberEgg3 from '../assets/art/ember-egg-3.webp';
import emberHatch from '../assets/art/ember-hatch.webp';
import emberHatchOpen from '../assets/art/ember-hatch-open.webp';
import emberWhelp from '../assets/art/ember-whelp2.webp';
import emberWhelpOpen from '../assets/art/ember-whelp2-open.webp';
import emberDrake from '../assets/art/ember-drake.webp';
import emberDrakeOpen from '../assets/art/ember-drake-open.webp';
import emberAdult from '../assets/art/ember-adult2.webp';
import emberAdultOpen from '../assets/art/ember-adult2-open.webp';

// Morph frame sets, generated by tools/dragon-morph (each is null until exported).
// One manifest per ART STYLE per dragon; the player picks the style on the select screen.
import { getArtStyle, ART_STYLES } from '../utils/artStyle';
import emberRealistic from '../assets/art/morph/ember/realistic';
import emberComic from '../assets/art/morph/ember/graphic-novel';
import emberPainterly from '../assets/art/morph/ember/painterly';
import morphFrost from '../assets/art/morph/frost';
import morphStone from '../assets/art/morph/stone';
import morphShadow from '../assets/art/morph/shadow';
import morphGlimmer from '../assets/art/morph/glimmer';
import morphStorm from '../assets/art/morph/storm';

// Studio-generated egg portraits — shared with DragonSelectScreen so the egg
// the player picks is the same egg they hatch in the game.
export const EGG_ART = {
  ember: eggEmber,
  frost: eggFrost,
  stone: eggStone,
  shadow: eggShadow,
  glimmer: eggGlimmer,
  storm: eggStorm,
};

// ---------------------------------------------------------------------------
// MORPH SETS (v2.8): one shared canvas, a NEW painted frame for every progress
// step — egg → cracks → hatchling → … → adult. No per-frame rescaling, no
// union crops: the pipeline exported every frame from the same crop box, so a
// crossfade between neighbours reads as the dragon actually growing.
// ---------------------------------------------------------------------------
const MORPH_SETS = {
  ember: { realistic: emberRealistic, 'graphic-novel': emberComic, painterly: emberPainterly },
  frost: { 'graphic-novel': morphFrost },
  stone: { 'graphic-novel': morphStone },
  shadow: { 'graphic-novel': morphShadow },
  glimmer: { 'graphic-novel': morphGlimmer },
  storm: { 'graphic-novel': morphStorm },
};

const valid = set => !!(set && set.frames && set.frames.length);

// The chosen style's set, or the first style this dragon has art for.
export function morphSetFor(dragon, style = getArtStyle()) {
  const sets = MORPH_SETS[dragon?.id] || {};
  if (valid(sets[style])) return sets[style];
  const alt = ART_STYLES.map(s => sets[s.id]).find(valid);
  return alt || null;
}

export function stylesAvailable(dragon) {
  const sets = MORPH_SETS[dragon?.id] || {};
  return ART_STYLES.filter(s => valid(sets[s.id])).map(s => s.id);
}

export function hasMorphArt(dragon) {
  return !!morphSetFor(dragon);
}

// Painted crack progression (img2img from the egg itself, one union-cropped
// canvas). Index = crackStage 0-3. Dragons without an entry fall back to the
// SVG CrackOverlay on their select-screen egg portrait.
const EGG_CRACK_ART = {
  ember: [emberEgg0, emberEgg1, emberEgg2, emberEgg3],
};

// v2.7 painted growth-stage sprites (kept as the fallback until a dragon has a
// morph set): hatchling -> whelp -> drake -> adult, aligned closed/open pairs.
const SPRITE_STAGES = {
  ember: [
    { at: 0, closed: emberHatch, open: emberHatchOpen },
    { at: 0.26, closed: emberWhelp, open: emberWhelpOpen },
    { at: 0.55, closed: emberDrake, open: emberDrakeOpen },
    { at: 0.85, closed: emberAdult, open: emberAdultOpen },
  ],
};

export function hasSpriteArt(dragon) {
  return hasMorphArt(dragon) || !!SPRITE_STAGES[dragon?.id];
}

// Last frame whose progress threshold has been reached.
function pickFrame(frames, progress) {
  let pick = frames[0];
  for (const f of frames) {
    if (progress + 1e-6 >= f.p) pick = f;
  }
  return pick;
}

const FILL = {
  position: 'absolute', inset: 0, width: '100%', height: '100%',
  objectFit: 'contain', objectPosition: 'center bottom', display: 'block',
};

function MorphSprite({ dragon, set, progress, size, maxWidth, chomping, mouthRef }) {
  const target = pickFrame(set.frames, progress);
  const { glow } = dragon.colors;
  const eggFrames = set.frames.filter(f => f.kind === 'egg');

  // THE RUMBLE (Ryan 9/5): each answer in the egg phase shakes the egg and steps through TWO
  // cumulative crack frames timed to the shake - the mid frame at the first jolt, the target at
  // the second. Outside the egg phase the target shows directly.
  const [shown, setShown] = useState(target);
  const [rumbling, setRumbling] = useState(false);
  useEffect(() => {
    if (target.kind !== 'egg' || shown === target) { setShown(target); return undefined; }
    const from = eggFrames.indexOf(shown), to = eggFrames.indexOf(target);
    const path = to > from ? eggFrames.slice(from + 1, to + 1) : [target];
    setRumbling(true);
    // the reveal frames flip fast (a fracture runs in a burst), then the egg settles
    const step = path.length > 8 ? 55 : path.length > 2 ? 170 : 380;   // LTX clip frames run at ~18 fps
    const timers = path.map((f, k) => setTimeout(() => setShown(f), 220 + k * step));
    timers.push(setTimeout(() => setRumbling(false), 220 + path.length * step + 350));
    return () => timers.forEach(clearTimeout);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [target]);
  const frame = shown;
  const isEgg = frame.kind === 'egg';
  const eggIndex = isEgg ? eggFrames.indexOf(frame) : 0;

  // The box keeps the canvas aspect so nothing is ever clipped; height budget =
  // `size`, but never wider than the column we live in.
  let boxH = size;
  let boxW = size * set.aspect;
  if (maxWidth && boxW > maxWidth) {
    boxW = maxWidth;
    boxH = boxW / set.aspect;
  }

  // Growth is gradual and organic: a slow crossfade and a barely-there swell on
  // each advance. The HATCH is the one allowed jolt (egg -> hatchling): a bigger
  // pop and a faster fade so it reads as a reveal, not a morph.
  const isHatch = !isEgg && progress > 0 && set.frames.some(f => f.kind === 'egg') &&
    frame === set.frames.find(f => f.kind === 'dragon');
  const fade = isHatch ? 0.18 : 0.6;
  const pulse = useAnimation();
  useEffect(() => {
    pulse.start(isHatch
      ? { scale: [0.7, 1.12, 0.97, 1], y: [18, -10, 3, 0], transition: { duration: 0.7, ease: 'easeOut' } }
      : { scale: [1, 1.02, 1], transition: { duration: 0.6, ease: 'easeInOut' } });
  }, [frame.p, isHatch, pulse]);

  // Idle life from generated clips: the frame's idle frames play back and forth at rest.
  const idleFrames = (!isEgg && frame.idle && frame.idle.length > 1) ? frame.idle : null;
  const [idleK, setIdleK] = useState(0);
  useEffect(() => {
    if (!idleFrames || chomping) return undefined;
    let k = 0, dir = 1;
    const t = setInterval(() => {
      k += dir;
      if (k >= idleFrames.length - 1 || k <= 0) dir = -dir;
      setIdleK(k);
    }, 140);
    return () => clearInterval(t);
  }, [idleFrames, chomping]);

  // Idle life: a blink every 3-7 s (the eyes-closed twin, when the set has one) and a rare stretch.
  const [blinking, setBlinking] = useState(false);
  useEffect(() => {
    if (isEgg || !frame.blink) return undefined;
    let open, close;
    const schedule = () => {
      open = setTimeout(() => {
        setBlinking(true);
        close = setTimeout(() => { setBlinking(false); schedule(); }, 130);
      }, 3000 + Math.random() * 4000);
    };
    schedule();
    return () => { clearTimeout(open); clearTimeout(close); };
  }, [isEgg, frame.blink]);
  useEffect(() => {
    if (isEgg) return undefined;
    const t = setInterval(() => {
      pulse.start({ scale: [1, 1.03, 0.995, 1], y: [0, -4, 1, 0], transition: { duration: 0.9, ease: 'easeInOut' } });
    }, 22000 + Math.random() * 16000);
    return () => clearInterval(t);
  }, [isEgg, pulse]);

  const glowPx = isEgg ? 12 + eggIndex * 5 : 0;

  return (
    <div style={{
      width: boxW, height: boxH, position: 'relative', overflow: 'visible',
      display: 'flex', alignItems: 'flex-end', justifyContent: 'center',
    }}>
      {/* Ground shadow keeps the sprite anchored to the painted cave floor */}
      <div style={{
        position: 'absolute', left: '18%', right: '18%', bottom: -4,
        height: boxH * 0.07, borderRadius: '50%',
        background: 'radial-gradient(ellipse, #000000aa 0%, transparent 70%)',
      }} />
      {/* The broken shell stays on the floor behind the dragon after the hatch (the nest) */}
      {!isEgg && set.remnants && (
        <img
          src={set.remnants}
          alt=""
          aria-hidden="true"
          style={{ ...FILL, opacity: 0.95, zIndex: 0 }}
        />
      )}
      {/* Aura glow in the dragon's element color, pulsing with the breath */}
      <motion.div
        animate={{ opacity: isEgg ? [0.8, 1, 0.8] : [0.65, 1, 0.65] }}
        transition={{ duration: 3, repeat: Infinity, ease: 'easeInOut' }}
        style={{
          position: 'absolute', inset: '-10%',
          background: `radial-gradient(ellipse at 50% 65%, ${glow}${isEgg ? '3a' : '2e'} 0%, transparent 62%)`,
          pointerEvents: 'none',
        }} />

      <motion.div animate={pulse} style={{ position: 'absolute', inset: 0, transformOrigin: '50% 100%' }}>
        <motion.div
          style={{ position: 'absolute', inset: 0, transformOrigin: '50% 100%' }}
          animate={isEgg
            ? (rumbling
              ? { rotate: [0, -6, 5, -4, 3, -2, 0], x: [0, -4, 4, -3, 3, -1, 0], y: [0, -3, 0, -2, 0, -1, 0] }
              : { rotate: eggIndex > 0 ? [-2.5, 2.5, -2.5] : [-1, 1, -1] })
            : chomping
              ? { scale: [1, 1.06, 0.97, 1.04, 1], y: [0, -6, 3, -2, 0] }
              // breathing = a chest swell from the feet up; NO vertical drift (a bob made a planted
              // dragon look like it was hovering - Iona 9/5)
              : { scaleY: [1, 1.025, 1], scaleX: [1, 1.008, 1], rotate: [0, -0.4, 0, 0.35, 0] }}
          transition={isEgg
            ? (rumbling
              ? { duration: 0.55, repeat: 2, ease: 'easeInOut' }
              : { duration: eggIndex > 0 ? 0.45 : 3, repeat: Infinity, ease: 'easeInOut' })
            : chomping
              ? { duration: 0.7, repeat: Infinity, repeatType: 'loop', ease: 'easeOut' }
              : {
                  scaleY: { duration: 3.2, repeat: Infinity, ease: 'easeInOut' },
                  scaleX: { duration: 3.2, repeat: Infinity, ease: 'easeInOut' },
                  rotate: { duration: 13, repeat: Infinity, ease: 'easeInOut' },
                }}
        >
          {/* Crossfade: the previous frame stays mounted underneath while the new one fades in */}
          <AnimatePresence initial={false}>
            <motion.img
              key={frame.p}
              src={frame.closed}
              alt={dragon.name}
              initial={{ opacity: 0 }}
              animate={{ opacity: chomping && frame.open ? 0 : 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: fade }}
              style={{ ...FILL, filter: isEgg ? `drop-shadow(0 8px ${glowPx}px ${glow}${eggIndex > 1 ? '88' : '55'})` : 'none' }}
            />
          </AnimatePresence>
          {idleFrames && (
            <img
              src={idleFrames[idleK]}
              alt=""
              aria-hidden="true"
              style={{ ...FILL, opacity: chomping || blinking ? 0 : 1, zIndex: 1 }}
            />
          )}
          {frame.open && (
            <img
              src={frame.open}
              alt=""
              aria-hidden="true"
              style={{ ...FILL, opacity: chomping ? 1 : 0, transition: 'opacity 0.1s', zIndex: 2 }}
            />
          )}
          {frame.blink && (
            <img
              src={frame.blink}
              alt=""
              aria-hidden="true"
              style={{ ...FILL, opacity: blinking && !chomping ? 1 : 0, transition: 'opacity 0.05s', zIndex: 3 }}
            />
          )}
          {/* Invisible mouth marker for FlyingAnswer targeting — per frame, since the mouth moves as it grows */}
          <div ref={mouthRef} style={{
            position: 'absolute', left: `${frame.mouth.x * 100}%`, top: `${frame.mouth.y * 100}%`,
            width: 2, height: 2, pointerEvents: 'none',
          }} />
        </motion.div>
      </motion.div>
    </div>
  );
}

// SVG crack lines — fallback for dragons without painted crack frames
function CrackOverlay({ crackStage, glow }) {
  return (
    <svg viewBox="0 0 100 130" style={{ position: 'absolute', inset: 0, width: '100%', height: '100%' }}>
      {crackStage >= 3 && (
        <ellipse cx="50" cy="60" rx="30" ry="40" fill={glow} opacity="0.28" />
      )}
      {crackStage >= 1 && (
        <path d="M 47 22 L 54 34 L 46 45 L 53 56" fill="none" stroke="#fff8e8"
          strokeWidth="1.6" strokeLinecap="round" opacity="0.85" />
      )}
      {crackStage >= 2 && (
        <>
          <path d="M 54 34 L 64 40 L 61 52" fill="none" stroke="#fff8e8"
            strokeWidth="1.3" strokeLinecap="round" opacity="0.75" />
          <path d="M 46 45 L 36 50 L 39 62" fill="none" stroke="#fff8e8"
            strokeWidth="1.3" strokeLinecap="round" opacity="0.75" />
        </>
      )}
      {crackStage >= 3 && (
        <>
          <path d="M 53 56 L 48 70 L 56 82" fill="none" stroke="#fffdf5"
            strokeWidth="2" strokeLinecap="round" opacity="0.95" />
          <path d="M 39 62 L 45 74" fill="none" stroke="#fff8e8"
            strokeWidth="1.4" strokeLinecap="round" opacity="0.8" />
        </>
      )}
    </svg>
  );
}

function SpriteEgg({ dragon, size, crackStage, mouthRef }) {
  const eggH = size * 0.5;
  const { glow } = dragon.colors;
  const crackFrames = EGG_CRACK_ART[dragon.id];
  // Glow intensifies as the hatch approaches
  const glowPx = 14 + crackStage * 10;
  return (
    <div style={{
      width: size, height: size, display: 'flex',
      alignItems: 'flex-end', justifyContent: 'center',
    }}>
      <motion.div
        style={{ position: 'relative', transformOrigin: '50% 95%' }}
        animate={{ rotate: crackStage > 0 ? [-2.5, 2.5, -2.5] : [-1, 1, -1] }}
        transition={{
          duration: crackStage > 0 ? 0.45 : 3,
          repeat: Infinity, ease: 'easeInOut',
        }}
      >
        <img
          src={crackFrames ? crackFrames[crackStage] : EGG_ART[dragon.id]}
          alt={`${dragon.name} egg`}
          style={{
            height: eggH, width: 'auto', display: 'block',
            filter: `drop-shadow(0 8px ${glowPx}px ${glow}${crackStage > 1 ? '88' : '55'})`,
          }}
        />
        {!crackFrames && <CrackOverlay crackStage={crackStage} glow={glow} />}
        {/* Invisible marker for FlyingAnswer targeting */}
        <div ref={mouthRef} style={{
          position: 'absolute', left: '50%', top: '40%',
          width: 2, height: 2, pointerEvents: 'none',
        }} />
      </motion.div>
    </div>
  );
}

export default function DragonSprite({ dragon, progress, size = 400, maxWidth, chomping = false, mouthRef }) {
  const morph = morphSetFor(dragon);
  if (morph) {
    return (
      <MorphSprite dragon={dragon} set={morph} progress={progress} size={size}
        maxWidth={maxWidth} chomping={chomping} mouthRef={mouthRef} />
    );
  }

  const stages = SPRITE_STAGES[dragon.id];
  const { glow } = dragon.colors;

  if (progress <= 0.15) {
    const crackStage = progress <= 0 ? 0 : Math.min(3, Math.ceil(progress / 0.05));
    return <SpriteEgg dragon={dragon} size={size} crackStage={crackStage} mouthRef={mouthRef} />;
  }

  const t = Math.min(1, (progress - 0.15) / 0.85);
  const stage = [...stages].reverse().find(s => t >= s.at) || stages[0];
  // Hatchling starts small (35%) and grows to full size
  const displaySize = size * (0.35 + t * 0.65);

  return (
    <div style={{
      width: size, height: size, display: 'flex',
      alignItems: 'flex-end', justifyContent: 'center',
    }}>
      <motion.div
        key={stage.at} // re-springs on stage change (growth pop)
        style={{ position: 'relative', transformOrigin: '50% 100%' }}
        initial={{ scale: 0.4, y: 25, opacity: 0 }}
        animate={chomping
          ? { scale: [1, 1.08, 0.96, 1.05, 1], y: [0, -8, 4, -3, 0], opacity: 1 }
          : { scale: 1, y: [0, -5, 0], scaleY: [1, 1.025, 1], opacity: 1 }
        }
        transition={chomping
          ? { duration: 0.7, repeat: Infinity, repeatType: 'loop', ease: 'easeOut' }
          : {
              scale: { type: 'spring', stiffness: 260, damping: 16 },
              opacity: { duration: 0.25 },
              y: { duration: 3, repeat: Infinity, ease: 'easeInOut' },
              scaleY: { duration: 3, repeat: Infinity, ease: 'easeInOut' },
            }
        }
      >
        {/* Ground shadow keeps the sprite anchored to the painted cave floor */}
        <div style={{
          position: 'absolute', left: '12%', right: '12%', bottom: -6,
          height: displaySize * 0.09, borderRadius: '50%',
          background: `radial-gradient(ellipse, #000000aa 0%, transparent 70%)`,
        }} />
        {/* Aura glow in the dragon's element color */}
        <div style={{
          position: 'absolute', inset: '-12%',
          background: `radial-gradient(ellipse at 50% 60%, ${glow}2e 0%, transparent 65%)`,
          pointerEvents: 'none',
        }} />
        {/* Closed/open pair stacked — opacity swap reads as the mouth opening */}
        <img
          src={stage.closed}
          alt={dragon.name}
          style={{
            height: displaySize, width: 'auto', display: 'block',
            opacity: chomping ? 0 : 1, transition: 'opacity 0.1s',
          }}
        />
        <img
          src={stage.open}
          alt=""
          aria-hidden="true"
          style={{
            position: 'absolute', left: 0, top: 0,
            height: displaySize, width: 'auto',
            opacity: chomping ? 1 : 0, transition: 'opacity 0.1s',
          }}
        />
        {/* Invisible mouth marker for FlyingAnswer targeting (center of face) */}
        <div ref={mouthRef} style={{
          position: 'absolute', left: '54%', top: '40%',
          width: 2, height: 2, pointerEvents: 'none',
        }} />
      </motion.div>
    </div>
  );
}
