"""Export stage: union-crop every frame to ONE shared box (so registration between frames is kept),
downsize, encode webp, write the JS manifest the app imports, and a scrub viewer for review."""
import json, os
from PIL import Image

import morph as M

OUT_W = 1024          # exported frame width (px)
QUALITY = 82
PAD = 10


def frame_list(pl, stage_only=False):
    """[(id, kind, p, closed_rgba, open_rgba|None)] for everything that exists."""
    out = []
    if not stage_only:
        for i, p in enumerate(M.EGG_P):
            f = pl.p("eggs", f"egg_{i}_rgba.png")
            if os.path.exists(f):
                out.append((f"e{i}", "egg", p, f, None))
    for i, p in enumerate(M.GROWTH_P):
        f = pl.p("morph", f"f{i:02d}_rgba.png")
        o = pl.p("chomp", f"f{i:02d}_open_rgba.png")
        if os.path.exists(f):
            out.append((f"f{i:02d}", "dragon", p, f, o if (os.path.exists(o) and not stage_only) else None))
    return out


def union_box(paths):
    x0 = y0 = 10 ** 9
    x1 = y1 = 0
    for p in paths:
        bb = M.alpha_bbox(Image.open(p).convert("RGBA"))
        if bb:
            x0, y0, x1, y1 = min(x0, bb[0]), min(y0, bb[1]), max(x1, bb[2]), max(y1, bb[3])
    return max(0, x0 - PAD), max(0, y0 - PAD), min(M.W, x1 + PAD), min(M.H, y1 + PAD)


def export_dragon(pl):
    frames = frame_list(pl)
    if not frames:
        M.log("  nothing to export")
        return
    # one folder per style so several art sets can coexist (Ryan 9/5: maybe a settings option to pick
    # the style; decided after the three Ember sets are reviewed)
    out_dir = os.path.join(M.ART, "morph", pl.name, pl.a.style)
    os.makedirs(out_dir, exist_ok=True)
    box = union_box([f[3] for f in frames] + [f[4] for f in frames if f[4]])
    bx0, by0, bx1, by1 = box
    cw, ch = bx1 - bx0, by1 - by0
    scale = min(1.0, OUT_W / cw)
    size = (round(cw * scale), round(ch * scale))
    mouths = M.load_json(pl.p("chomp", "mouth.json"), {})
    # facing vote across the frames: a left-facing dragon is mirrored so it looks toward the questions
    votes = [m.get("facing") for m in mouths.values()]
    mirror = votes.count("left") > votes.count("right")
    M.log(f"  facing votes {dict((v, votes.count(v)) for v in set(votes))} -> {'MIRROR' if mirror else 'as drawn'}")

    def write(src, name):
        im = Image.open(src).convert("RGBA").crop(box)
        if scale < 1:
            im = im.resize(size, Image.LANCZOS)
        if mirror:
            im = im.transpose(Image.FLIP_LEFT_RIGHT)
        im.save(os.path.join(out_dir, name), "WEBP", quality=QUALITY, method=6)
        return name

    imports, entries, total = [], [], 0
    for fid, kind, p, closed, opened in frames:
        cname = write(closed, f"{fid}.webp")
        imports.append(f"import {fid} from './{cname}';")
        oname = None
        if opened:
            oname = write(opened, f"{fid}o.webp")
            imports.append(f"import {fid}o from './{oname}';")
        bname = None
        bsrc = pl.p("blink", f"{fid}_blink_rgba.png") if kind == "dragon" else None
        if bsrc and os.path.exists(bsrc):
            bname = write(bsrc, f"{fid}b.webp")
            imports.append(f"import {fid}b from './{bname}';")
        # mouth anchor as a fraction of the exported crop
        if kind == "dragon" and fid[1:] in mouths:
            mi = mouths[fid[1:]]
            mx, my = (mi["cx"] * M.W - bx0) / cw, (mi["cy"] * M.H - by0) / ch
        else:
            bb = M.alpha_bbox(Image.open(closed).convert("RGBA"))
            mx = ((bb[0] + bb[2]) / 2 - bx0) / cw
            my = (bb[1] + (bb[3] - bb[1]) * (0.42 if kind == "egg" else 0.3) - by0) / ch
        if mirror:
            mx = 1 - mx
        entries.append(f"  {{ p: {p}, kind: '{kind}', closed: {fid}, open: {fid + 'o' if oname else 'null'}, "
                       f"blink: {fid + 'b' if bname else 'null'}, mouth: {{ x: {mx:.4f}, y: {my:.4f} }} }},")
        total += os.path.getsize(os.path.join(out_dir, cname)) + (os.path.getsize(os.path.join(out_dir, oname)) if oname else 0)

    # the select-screen portrait = the solid crust egg (frame 0) at generation size, so the egg the
    # player picks IS the egg that hatches
    portrait = pl.p("eggs", "egg_0_gen_rgba.png")
    has_portrait = os.path.exists(portrait)
    if has_portrait:
        im = Image.open(portrait).convert("RGBA")
        bb = M.alpha_bbox(im)
        im = im.crop(bb)
        if mirror:
            im = im.transpose(Image.FLIP_LEFT_RIGHT)
        im.thumbnail((600, 600), Image.LANCZOS)
        im.save(os.path.join(out_dir, "egg.webp"), "WEBP", quality=QUALITY, method=6)
        imports.append("import eggPortrait from './egg.webp';")

    js = ("// GENERATED by tools/dragon-morph/morph.py --stage export - do not edit by hand.\n"
          "// Every frame shares one canvas crop, so the app never rescales between frames.\n"
          + "\n".join(imports) + "\n\nconst FRAMES = [\n" + "\n".join(entries) + "\n];\n\n"
          f"export default {{ aspect: {size[0] / size[1]:.4f}, width: {size[0]}, height: {size[1]}, "
          f"mirrored: {'true' if mirror else 'false'}, eggPortrait: {'eggPortrait' if has_portrait else 'null'}, "
          f"frames: FRAMES }};\n")
    with open(os.path.join(out_dir, "index.js"), "w", encoding="utf-8") as f:
        f.write(js)
    M.log(f"  {len(frames)} frames -> {os.path.relpath(out_dir, M.REPO)} ({total/1024:.0f} KB, crop {size[0]}x{size[1]})")
    write_viewer(pl, stage_only=False)


def write_viewer(pl, stage_only=False):
    """A file:// scrub viewer: slider through the frames, autoplay, chomp toggle, onion skin."""
    frames = frame_list(pl, stage_only=False) if stage_only else frame_list(pl)
    frames = [f for f in frames] if frames else []
    if not frames:
        return
    if stage_only:
        def rel_or_none(i):
            o = pl.p("chomp", f"f{i:02d}_open_rgba.png")
            return os.path.relpath(o, pl.work).replace("\\", "/") if os.path.exists(o) else None
        items = [{"id": f[0], "p": f[2], "closed": os.path.relpath(f[3], pl.work).replace("\\", "/"),
                  "open": rel_or_none(int(f[0][1:])) if f[1] == "dragon" else None} for f in frames]
        title = f"{pl.name} - review (work copies)"
    else:
        rel = os.path.relpath(os.path.join(M.ART, "morph", pl.name, pl.a.style), pl.work).replace("\\", "/")
        items = [{"id": f[0], "p": f[2], "closed": f"{rel}/{f[0]}.webp",
                  "open": f"{rel}/{f[0]}o.webp" if f[4] else None} for f in frames]
        title = f"{pl.name} - exported frames"
    html = f"""<!doctype html><meta charset="utf-8"><title>{title}</title>
<style>
 body{{margin:0;background:#0D1B2A;color:#cfd8e3;font:14px system-ui}}
 #stage{{position:relative;height:72vh;display:flex;align-items:flex-end;justify-content:center;background:radial-gradient(ellipse at 50% 80%,#1E2E42,#0D1B2A)}}
 #stage img{{position:absolute;bottom:4vh;max-height:64vh;max-width:96vw}}
 #onion{{opacity:.35;filter:grayscale(1)}}
 #bar{{padding:14px 18px;display:flex;gap:14px;align-items:center;flex-wrap:wrap}}
 input[type=range]{{flex:1;min-width:260px}}
 button{{background:#1E4A7A;color:#fff;border:0;border-radius:10px;padding:8px 14px;font-weight:700}}
 #label{{font-weight:700;color:#00A7E1;min-width:180px}}
</style>
<div id="stage"><img id="onion" alt=""><img id="cur" alt=""><img id="open" alt="" hidden></div>
<div id="bar">
 <span id="label"></span>
 <input id="s" type="range" min="0" max="{len(items)-1}" value="0">
 <button id="play">play</button>
 <label><input id="ck" type="checkbox"> chomp</label>
 <label><input id="on" type="checkbox" checked> onion skin</label>
 <label>ms <input id="ms" type="number" value="220" style="width:70px"></label>
</div>
<script>
const F={json.dumps(items)};
const s=document.getElementById('s'),cur=document.getElementById('cur'),onion=document.getElementById('onion'),
 op=document.getElementById('open'),lab=document.getElementById('label'),ck=document.getElementById('ck'),
 on=document.getElementById('on'),ms=document.getElementById('ms');let timer=null;
F.forEach(f=>{{new Image().src=f.closed; if(f.open) new Image().src=f.open;}});
function show(i){{const f=F[i];cur.src=f.closed;onion.src=i>0?F[i-1].closed:'';onion.hidden=!on.checked||i===0;
 lab.textContent=f.id+'  p='+f.p+(f.open?'  (has open)':'');
 if(f.open&&ck.checked){{op.src=f.open;op.hidden=false;cur.style.opacity=0;}}else{{op.hidden=true;cur.style.opacity=1;}}}}
s.oninput=()=>show(+s.value);ck.onchange=on.onchange=()=>show(+s.value);
document.getElementById('play').onclick=e=>{{if(timer){{clearInterval(timer);timer=null;e.target.textContent='play';return;}}
 e.target.textContent='stop';timer=setInterval(()=>{{s.value=(+s.value+1)%F.length;show(+s.value);}},+ms.value||220);}};
document.addEventListener('keydown',e=>{{if(e.key==='ArrowRight')s.value=Math.min(F.length-1,+s.value+1);
 if(e.key==='ArrowLeft')s.value=Math.max(0,+s.value-1);if(e.key===' ')ck.checked=!ck.checked;show(+s.value);}});
show(0);
</script>"""
    path = pl.p("viewer.html" if not stage_only else "viewer-morph.html")
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    M.log(f"  viewer -> {os.path.relpath(path, M.HERE)}  (open in a browser, arrow keys scrub, space = chomp)")
